# http://www.appveyor.com/docs/appveyor-yml
build: false
shallow_clone: true
platform:
    - x86
    - x64
clone_folder: C:\projects\os-filter-obj

cache:
    - C:\tools\php -> appveyor.yml

init:
    - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
      - IF EXIST c:\tools\php (SET PHP=0)
      - IF %PHP%==1 cinst -y OpenSSL.Light
      - IF %PHP%==1 cinst php --version 7.0.9
      - ps: Set-Service wuauserv -StartupType Manual
      - cd c:\tools\php
      - IF %PHP%==1 copy php.ini-production php.ini /Y
      - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
      - IF %PHP%==1 echo memory_limit=1024M >> php.ini
      - IF %PHP%==1 echo extension_dir=ext >> php.ini
      - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
      - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
      - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
      - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
      - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
      - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
      - cd c:\projects\os-filter-obj
      - appveyor-retry composer install --prefer-dist --no-progress

branches:
    except:
        - gh-pages

before_test:
    - php --version

test_script:
    - cd c:\projects\os-filter-obj
    - vendor/bin/phpunit -c phpunit.xml.dist
